---
 - hosts: localhost
   become: true
   become_method: sudo
   become_user: root
   tasks:
   - name: "example cronjob"
     ansible.builtin.cron:
      name: "test"
      state: present
      minute: "*"
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      user: root
      job: "ansible-playbook /home/ubuntu/start.yml"
      #      cron_file: ansible_yum-autoupdate       create a log file in /etc/cron.d/ path
